language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm config set spin false
  - npm install -g grunt-cli
script:
  - grunt spec --gruntfile ui/Gruntfile.js
  - grunt spec --gruntfile service/Gruntfile.js
